name: Build and Test

on:
  push:
    branches:
      - main
      - "*"
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update apt package list
        run: sudo apt-get update

      - name: Reset apt sources to defaults (if needed)
        run: |
          sudo mv /etc/apt/sources.list /etc/apt/sources.list.bak || true
          sudo bash -c 'echo "deb http://archive.ubuntu.com/ubuntu jammy main universe restricted multiverse" > /etc/apt/sources.list'
          sudo bash -c 'echo "deb http://archive.ubuntu.com/ubuntu jammy-updates main universe restricted multiverse" >> /etc/apt/sources.list'
          sudo bash -c 'echo "deb http://security.ubuntu.com/ubuntu jammy-security main universe restricted multiverse" >> /etc/apt/sources.list'
          sudo apt-get update

      - name: Install Dependencies (LLVM, Ninja, CURL, libcurl-dev)
        run: sudo apt-get install -y --fix-missing llvm clang curl ninja-build libcurl4-openssl-dev

      - name: Configure CMake
        run: cmake -S comparer -B comparer/build -G Ninja -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++

      - name: Build with Ninja
        run: cmake --build comparer/build

      - name: Configure Tests
        run: cmake -S comparer/tests -B comparer/tests/build -G Ninja -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++

      - name: Build Tests
        run: cmake --build comparer/tests/build

      - name: Run Tests
        run: ctest --test-dir comparer/tests/build --output-on-failure -V