name: Build and Test

on:
  push:
    branches:
      - main
      - "*"
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1

      - name: Set up Ninja
        uses: ashutoshvarma/setup-ninja@v1

      - name: Install LLVM
        run: sudo apt-get install -y llvm clang curl

      - name: Configure CMake
        run: cmake -S comparer -B comparer/build -G Ninja -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++

      - name: Build with Ninja
        run: cmake --build comparer/build

      - name: Configure Tests
        run: cmake -S comparer/tests -B comparer/tests/build -G Ninja -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++

      - name: Build Tests
        run: cmake --build comparer/tests/build

      - name: Run Tests
        run: ctest --test-dir comparer/tests/build --output-on-failure -V
