name: CI/CD Pipeline

on:
  push:
    branches: 
      - '**'  # Triggers for every branch
  pull_request:
    branches:
      - main  # Only triggers for pull requests targeting 'main'

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        compiler: [clang]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1.10

      - name: Setup compiler on Ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y clang curl libcurl4-openssl-dev

      - name: Setup compiler on Windows
        if: matrix.os == 'windows-latest'
        run: |
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' --yes
          choco install ninja --yes
          choco install curl --yes

      - name: Configure (CMake)
        run: |
          cmake -S comparer -B comparer/build -G Ninja

      - name: Build (CMake)
        run: |
          cmake --build comparer/build

      - name: Configure Tests (CMake)
        run: |
          cmake -S comparer/tests -B comparer/tests/build -G Ninja

      - name: Build Tests (CMake)
        run: |
          cmake --build comparer/tests/build

      - name: Run Unit Tests
        run: |
          ctest --test-dir comparer/tests/build